### ISSUE TITLE
Buying ammo by a bind

### ISSUE THREAD

**Issue by SVB0Y** [Ecco-SC/Ecco#4]
hello, wouldn't it be quite handy if, there was a way of buying ammo for the current weapon youre holding by just one click? instead of buying a weapon and then scrolling through the buy ammo section, you could just save time by pressing a bind which does everything for you, its especially useful for big buy menu packs which feature over 50+ weapons, thanks

**Comment by DrAbcOfficial** [comment]
finished in 29e155d
You must open EchoAmmo.as edit the correspondence between the weapon and echo script.
