### ISSUE TITLE
Just a little help need here

### ISSUE THREAD

**Issue by RedyRT** [Ecco-SC/Ecco#6]
In which right way i need to use buy_ammo_item command? just typing in chat it not working in game, when tried to use it someway in .echo - not working. btw i added my weapon in EchoAmmo.as dictionary

**Comment by RedyRT** [comment]
Umm, yes i uncommented line about echoammo in include.as 
![изображение](https://user-images.githubusercontent.com/64935439/211092600-8d25f0fc-04a1-451b-84f5-53630d23d47d.png)
Then added dictionary key-value pairs (btw i named it with the same name of the weapon for .echo scripts)
![изображение](https://user-images.githubusercontent.com/64935439/211092690-c88a7ceb-138d-45fb-8be2-1273aa34e869.png)
Then i just created for example buyammoname.echo and i added a command buy_ammo_item here 
![изображение](https://user-images.githubusercontent.com/64935439/211092925-4bcfe001-07e0-46b4-ab44-3bc0cef8415e.png)
But when i holding that weapon and trying to buy ammo it just giving me nothing 
![изображение](https://user-images.githubusercontent.com/64935439/211093037-0c20697e-f835-4cd1-9323-da091bed74ba.png)

**Comment by DrAbcOfficial** [comment]
Ah, that's because you put the files in a subfolder
The value in the echoammo.as dictionary is actually the path
so you just need to add the subfolder to the key-value pair
For example:
"weapon_ins2usp", "Ammo/amno_45ACP"

**Comment by RedyRT** [comment]
> 

Thank you very much, it worked ^^.

**Comment by RedyRT** [comment]
> Ah, that's because you put the files in a subfolder The value in the echoammo.as dictionary is actually the path so you just need to add the subfolder to the key-value pair For example: "weapon_ins2usp", "Ammo/ammo_45ACP"

btw, just one thing is it possible to make fast buy ammo with the cost that i choosed in .echo ammo file?
